toolbox/models.py
# written by brian.
# database models relevant to the program. explanations:
#   User is to store user credentials returned from the auth0 json.
#    - During use, the json is stored in the Flask session, so we can use that to creat queries
#   SessionHistory stores a UUID as its PK, which corresponds to a subfolder in 'uploads'
#	 - During use, files are uploaded to that directory
#    - Files stay there, allowing the user to delete whole "sessions" at their discretion

# pip packages. connected to Flask-SQLAlchemy
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

# local
from toolbox import db

class User(db.Model):
	__tablename__ = "users"

	# user credentials, ripped from auth0 json
	user_id = db.Column(db.String, primary_key=True)
	username = db.Column(db.String, unique=True, nullable=False)
	email = db.Column(db.String, unique=True, nullable=False)
	admin = db.Column(db.Boolean, nullable=False, default=False)

	# Define relationships to session histories (UUID-folderpaths)
	session_histories = relationship("SessionHistory", backref="user", lazy=True)

class SessionHistory(db.Model):
	__tablename__ = "session_history"

	# metadata; session_id is actually a UUID with a corresponding folder in uploads/
	session_id = db.Column(db.String, primary_key=True)
	user_id = db.Column(db.String, ForeignKey("users.user_id"), nullable=False)
	session_name = db.Column(db.String, nullable=True, default="VEDB Session")

toolbox/__init__.py
# written by brian
# this file serves as the system "master", doing:
#   connecting with the subsystems (Flask Blueprints)
#   registering all the extensions used in the application
#   minifies everything to serve it easier
# this rewrite was made possible with:
# guide: https://hackersandslackers.com/flask-application-factory/
# guide: https://github.com/app-generator/flask-datta-able

# base
from importlib import import_module

# flask and its plugins
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_minify import Minify
from flask_wtf.csrf import CSRFProtect

# globally accessible objects
db = SQLAlchemy()
csrf = CSRFProtect()

def register_extensions(app):
    db.init_app(app)
    csrf.init_app(app)

# registers blueprints in a generalized manner. idea by chatgpt
def register_blueprints(app, bp_list):
    for module_name in bp_list:
        module = import_module('toolbox.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)

def create_app(test_config=None):
    # initialize core application
    app = Flask(__name__, instance_relative_config=True)

    # configuration
    if test_config is None:
        app.config.from_object("toolbox.config.Config")
    elif test_config:
        app.config.from_object("toolbox.config.TestingConfig")

    # minifies files within the project for faster serving
    Minify(app, html=True, js=True, cssless=True)

    register_extensions(app)

    # blueprints. these are the aforementioned "subsystems" found in our project
    blueprint_list = ["home", "user_auth", "file_upload", "visualizer", "dashboard"]
    register_blueprints(app, blueprint_list)

    with app.app_context():
        db.create_all()
        
    return app

toolbox/file_upload/routes.py
# written by brian, with inspiration from matt's original design (the variable-checking)
# in the midst of a rewrite for more robust handling of files in general

# base
import uuid

# flask
from flask import render_template, flash, request, redirect, jsonify

# local
from toolbox.file_upload import blueprint
from toolbox.file_upload.forms import *
from toolbox.file_upload.methods import *

# create uploads directory if it doesn't already exist
UPLOAD_FOLDER = 'uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@blueprint.before_request
def create_user_directory():
    # Only generate a new UUID if it's not already in the session
    if 'upload_uuid' not in session:
        session['upload_uuid'] = str(uuid.uuid4())
    request.uuid = session['upload_uuid']

    # designate an upload folder, creating it if it doesn't exist
    request.upload_path = os.path.join(UPLOAD_FOLDER, request.uuid)
    if not os.path.exists(request.upload_path):
        remove_empty_dirs(UPLOAD_FOLDER)
        os.makedirs(request.upload_path, exist_ok=True)
    
    print(f"Using this folder: {request.upload_path}")

@blueprint.route("/file_upload", methods=["GET", "POST"])
def file_upload():
    # check if user is logged in, redirecting back to the homepage if not
    if check_redirect := check():
        return check_redirect

    # forms
    databraryurl = DatabraryURLForm()
    osfurl = OSFURLForm()
    visualizer_button = EnterVisualizer()
    reset_button = ResetFileUpload()

    # initialized boolean flags dictionary to check if both forms are submitted
    data_submitted = False
    videos_submitted = False
    
    # url handling
    if databraryurl.validate_on_submit() and databraryurl.dtb_submit.data:  # If Databrary form is valid
        # Attempt to fetch and unzip Databrary video files
        dtb_extraction_path = fetch_and_unzip(download_databrary_videos, databraryurl.dtb_url.data, request.upload_path)
        
        if "Error" in dtb_extraction_path:
            flash(f"Error processing Databrary files: {dtb_extraction_path}", 'error')
        else:
            flash(f"Videos from Databrary stored in: {dtb_extraction_path}")
            videos_submitted = True
    
    if osfurl.validate_on_submit() and osfurl.osf_submit.data:  # If OSF form is valid
        # Attempt to fetch and unzip OSF data files
        osf_extraction_path = fetch_and_unzip(download_osf_data, osfurl.osf_url.data, request.upload_path)
        
        if "Error" in osf_extraction_path:
            flash(f"Error processing OSF files: {osf_extraction_path}", 'error')
        else:
            flash(f"Data from OSF stored in: {osf_extraction_path}")
            data_submitted = True

    # On submit of both fields AKA dictionary has all True values
    if visualizer_button.validate_on_submit() and visualizer_button.submit.data and data_submitted and videos_submitted:
        add_session_to_db(request.uuid)
        session.pop('upload_uuid', None)
        return redirect("/visualizer")
    
    # On submit, it will delete whatever has been uploaded to request.upload_path folder
    if reset_button.validate_on_submit() and reset_button.reset.data:
        clear_directory(request.upload_path)
        data_submitted = False
        videos_submitted = False
        
    # Render the file upload page
    return render_template("file_upload/file_upload.html",
        is_admin=is_admin(),
        
        # flags and other variables
        data_submitted=data_submitted,
        videos_submitted=videos_submitted,
        
        # forms and buttons
        databraryurl=databraryurl,
        osfurl=osfurl,
        visualizer_button=visualizer_button,
        reset_button=reset_button
    )

@blueprint.route('/upload', methods=['POST'])
def upload_file():
    
    if 'filepond' not in request.files:
        return jsonify({'error': 'No file part'}), 400

    file = request.files['filepond']
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400

    # Save the file to the user's uuid upload folder
    file.save(os.path.join(request.upload_path, file.filename))

    return jsonify({'id': file.filename})

toolbox/home/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    "home_bp", __name__,
    template_folder="templates",
    static_folder="static"
)

toolbox/home/routes.py
# written by brian, basic routing table for the "dumb" pages

# flask
from flask import render_template

# local
from toolbox.home import blueprint

@blueprint.route("/")
def home():
    return render_template("home/home.html")

@blueprint.route("/team")
def team():
    return render_template("home/team.html")

@blueprint.route("/faculty")
def faculty():
    return render_template("home/faculty.html")

@blueprint.app_errorhandler(404)
def page_not_found(e):
    return render_template("home/404.html"), 404

@blueprint.app_errorhandler(500)
def something_went_wrong(e):
    return render_template("home/500.html"), 500

toolbox/visualizer/routes.py
# flask and its plugins
from flask import render_template

# local
from toolbox.visualizer import blueprint

@blueprint.route("/visualizer")
def visualizer():
    return render_template("visualizer/visualizer.html")

toolbox/templates/file_upload_bp/base.jinja
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='home_bp/img/vedb.png') }}">
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='home_bp/img/favicon.png') }}">
        <title>{% block title %}{% endblock %} - VEDB Toolbox</title>
        
        <!--     Fonts and icons     -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900" />
        <!-- Nucleo Icons -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home_bp/css/nucleo-icons.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home_bp/css/nucleo-svg.css') }}" />

        <!-- Material Icons -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
        <!-- CSS Files -->
        <link id="pagestyle" href="{{ url_for('static', filename='home_bp/css/material-kit.css') }}" rel="stylesheet" />
    </head>

    <body class="index-page bg-gray-200">
    <!-- Navbar -->
        <div class="container position-sticky z-index-sticky top-0">
            <div class="row">
                <div class="col-12">
                    <nav class="navbar navbar-expand-lg blur border-radius-xl top-0 z-index-fixed shadow position-relative my-3 p-2 start-0 end-0 mx-4">
                        <div class="container-fluid px-0">
                            <a class="navbar-brand font-weight-bolder ms-sm-3 text-sm" href="{{ url_for('home_bp.home') }}" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
                            VEDB Toolbox
                            </a>
                            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon mt-2">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                            </span>
                            </button>
                            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
                                <ul class="navbar-nav navbar-nav-hover ms-auto">
                                    <li class="nav-item dropdown dropdown-hover mx-2">
                                        <a class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold" id="dropdownMenuDocs" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="material-symbols-rounded opacity-6 me-2 text-md">person</i>
                                        People
                                        <img src="{{ url_for('static', filename='home_bp/img/down-arrow-dark.svg') }}" alt="down-arrow" class="arrow ms-auto ms-md-2">
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-animation dropdown-md dropdown-md-responsive mt-0 mt-lg-3 p-3 border-radius-lg" aria-labelledby="dropdownMenuDocs">
                                            <div class="d-none d-lg-block">
                                                <ul class="list-group">
                                                    <li class="nav-item list-group-item border-0 p-0">
                                                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="{{ url_for('home_bp.team') }}">
                                                            <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Team</h6>
                                                            <span class="text-sm">The team behind the Toolbox!</span>
                                                        </a>
                                                    </li>
                                                    <li class="nav-item list-group-item border-0 p-0">
                                                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="{{ url_for('home_bp.faculty') }}">
                                                            <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Faculty</h6>
                                                            <span class="text-sm">Our advisors and instructors!</span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="row d-lg-none">
                                                <div class="col-md-12 g-0">
                                                    <a class="dropdown-item py-2 ps-3 border-radius-md" href="{{ url_for('home_bp.team') }}">
                                                        <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Team</h6>
                                                        <span class="text-sm">The team behind the Toolbox!</span>
                                                    </a>
                                                    <a class="dropdown-item py-2 ps-3 border-radius-md" href="{{ url_for('home_bp.faculty') }}">
                                                        <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Faculty</h6>
                                                        <span class="text-sm">Our advisors and instructors!</span>
                                                    </a>
                                                </div>
                                            </div>
                                        </ul>
                                    </li>

                                    <li class="nav-item ms-lg-auto">
                                        <a class="nav-link nav-link-icon me-2" href="https://github.com/Gaskell-Matthew-1102/VEDB-Toolbox" target="_blank">
                                            <i class="fa fa-github me-1"></i>
                                            <img src="{{ url_for('static', filename='home_bp/img/github.png') }}" width="24" height="24" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Check us out on Github" />                                        </a>
                                    </li>
                                    {% if session %}
                                    <li class="nav-item my-auto ms-3 ms-lg-0">
                                        <a href="{{ url_for('visualizer_bp.visualizer') }}" class="btn bg-gradient-light mb-0 mt-2 mt-md-0">Enter Visualizer</a>
                                    </li>
                                    <li class="nav-item my-auto ms-3 ms-lg-0">
                                        <a href="{{ url_for('auth_bp.logout') }}" class="btn bg-gradient-dark mb-0 mt-2 mt-md-0">Log out</a>
                                    </li>
                                    {% else %}
                                    <li class="nav-item my-auto ms-3 ms-lg-0">
                                        <a href="{{ url_for('auth_bp.login') }}" class="btn bg-gradient-dark mb-0 mt-2 mt-md-0">Sign in</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </nav>
                    <!-- End Navbar -->
                </div>
            </div>
        </div>

        <!-- real body -->
        <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-4">
            {% block content %}{% endblock %}
        </div>
        <!-- end real body -->

        <!-- footer -->
        <footer class="footer pt-5 mt-5">
            <div class="container">
                <div class=" row">
                    <div class="col-12">
                        <div class="text-center">
                            <p class="text-dark my-4 text-sm font-weight-normal">
                                All rights reserved. Copyright © <script>document.write(new Date().getFullYear())</script> VEDB Toolbox by Team 16 of UNR's 2024-25 Senior Projects course</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end footer -->

        <!--   Bootstrap from CDN   -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        <!-- Scroll bar -->
        <script src="https://cdn.jsdelivr.net/npm/perfect-scrollbar@1.5.6/dist/perfect-scrollbar.min.js"></script>

        <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
        <script src="https://cdn.jsdelivr.net/gh/dixonandmoe/rellax@master/rellax.min.js"></script>

        <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tilt.js/1.2.1/tilt.jquery.min.js"></script>

        <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
        <script src="{{ url_for('static', filename='home_bp/js/material-kit.min.js') }}" type="text/javascript"></script>
    </body>
</html>

toolbox/templates/visualizer_bp/base.jinja
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='home_bp/img/vedb.png') }}">
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='home_bp/img/favicon.png') }}">
        <title>{% block title %}{% endblock %} - VEDB Toolbox</title>
        
        <!--     Fonts and icons     -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700,900" />
        <!-- Nucleo Icons -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home_bp/css/nucleo-icons.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home_bp/css/nucleo-svg.css') }}" />

        <!-- Material Icons -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,400,0,0" />
        <!-- CSS Files -->
        <link id="pagestyle" href="{{ url_for('static', filename='home_bp/css/material-kit.css') }}" rel="stylesheet" />
    </head>

    <body class="index-page bg-gray-200">
    <!-- Navbar -->
        <div class="container position-sticky z-index-sticky top-0">
            <div class="row">
                <div class="col-12">
                    <nav class="navbar navbar-expand-lg blur border-radius-xl top-0 z-index-fixed shadow position-relative my-3 p-2 start-0 end-0 mx-4">
                        <div class="container-fluid px-0">
                            <a class="navbar-brand font-weight-bolder ms-sm-3 text-sm" href="{{ url_for('home_bp.home') }}" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom" target="_blank">
                            VEDB Toolbox
                            </a>
                            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon mt-2">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                            </span>
                            </button>
                            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
                                <ul class="navbar-nav navbar-nav-hover ms-auto">
                                    <li class="nav-item dropdown dropdown-hover mx-2">
                                        <a class="nav-link ps-2 d-flex cursor-pointer align-items-center font-weight-semibold" id="dropdownMenuDocs" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="material-symbols-rounded opacity-6 me-2 text-md">person</i>
                                        People
                                        <img src="{{ url_for('static', filename='home_bp/img/down-arrow-dark.svg') }}" alt="down-arrow" class="arrow ms-auto ms-md-2">
                                        </a>
                                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-animation dropdown-md dropdown-md-responsive mt-0 mt-lg-3 p-3 border-radius-lg" aria-labelledby="dropdownMenuDocs">
                                            <div class="d-none d-lg-block">
                                                <ul class="list-group">
                                                    <li class="nav-item list-group-item border-0 p-0">
                                                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="{{ url_for('home_bp.team') }}">
                                                            <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Team</h6>
                                                            <span class="text-sm">The team behind the Toolbox!</span>
                                                        </a>
                                                    </li>
                                                    <li class="nav-item list-group-item border-0 p-0">
                                                        <a class="dropdown-item py-2 ps-3 border-radius-md" href="{{ url_for('home_bp.faculty') }}">
                                                            <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Faculty</h6>
                                                            <span class="text-sm">Our advisors and instructors!</span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <div class="row d-lg-none">
                                                <div class="col-md-12 g-0">
                                                    <a class="dropdown-item py-2 ps-3 border-radius-md" href="{{ url_for('home_bp.team') }}">
                                                        <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Team</h6>
                                                        <span class="text-sm">The team behind the Toolbox!</span>
                                                    </a>
                                                    <a class="dropdown-item py-2 ps-3 border-radius-md" href="{{ url_for('home_bp.faculty') }}">
                                                        <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-cente align-items-center p-0">Faculty</h6>
                                                        <span class="text-sm">Our advisors and instructors!</span>
                                                    </a>
                                                </div>
                                            </div>
                                        </ul>
                                    </li>

                                    <li class="nav-item ms-lg-auto">
                                        <a class="nav-link nav-link-icon me-2" href="https://github.com/Gaskell-Matthew-1102/VEDB-Toolbox" target="_blank">
                                            <i class="fa fa-github me-1"></i>
                                            <img src="{{ url_for('static', filename='home_bp/img/github.png') }}" width="24" height="24" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Check us out on Github" />                                        </a>
                                    </li>
                                    {% if session %}
                                    <li class="nav-item my-auto ms-3 ms-lg-0">
                                        <a href="{{ url_for('visualizer_bp.visualizer') }}" class="btn bg-gradient-light mb-0 mt-2 mt-md-0">Enter Visualizer</a>
                                    </li>
                                    <li class="nav-item my-auto ms-3 ms-lg-0">
                                        <a href="{{ url_for('auth_bp.logout') }}" class="btn bg-gradient-dark mb-0 mt-2 mt-md-0">Log out</a>
                                    </li>
                                    {% else %}
                                    <li class="nav-item my-auto ms-3 ms-lg-0">
                                        <a href="{{ url_for('auth_bp.login') }}" class="btn bg-gradient-dark mb-0 mt-2 mt-md-0">Sign in</a>
                                    </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </nav>
                    <!-- End Navbar -->
                </div>
            </div>
        </div>

        <!-- real body -->
        <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-4">
            {% block content %}{% endblock %}
        </div>
        <!-- end real body -->

        <!-- footer -->
        <footer class="footer pt-5 mt-5">
            <div class="container">
                <div class=" row">
                    <div class="col-12">
                        <div class="text-center">
                            <p class="text-dark my-4 text-sm font-weight-normal">
                                All rights reserved. Copyright © <script>document.write(new Date().getFullYear())</script> VEDB Toolbox by Team 16 of UNR's 2024-25 Senior Projects course</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end footer -->

        <!--   Bootstrap from CDN   -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        <!-- Scroll bar -->
        <script src="https://cdn.jsdelivr.net/npm/perfect-scrollbar@1.5.6/dist/perfect-scrollbar.min.js"></script>

        <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
        <script src="https://cdn.jsdelivr.net/gh/dixonandmoe/rellax@master/rellax.min.js"></script>

        <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tilt.js/1.2.1/tilt.jquery.min.js"></script>

        <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
        <script src="{{ url_for('static', filename='home_bp/js/material-kit.min.js') }}" type="text/javascript"></script>
    </body>
</html>